mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin



urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
from django.db import models
from django.utils import timezone

from django.utils.encoding import  python_2_unicode_compatible
# Create your models here.

class Name_of_quiz(models.Model):
    Name = models.CharField(max_length=20)
    Grand = models.CharField(max_length=200)
    Date_of_public = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.Name


class Name_of_Question(models.Model):
    Date_of_Add = models.DateTimeField(default=timezone.now)
    Membership_of_Question = models.ForeignKey(Name_of_quiz, on_delete=models.CASCADE)
    Text_of_Question = models.CharField(max_length=255, default=None, blank=True)
    Image_of_Question = models.ImageField(default=None, blank=True)
    Correct_Answer = models.CharField(max_length=255)
    def __str__(self):
        return self.Text_of_Question

class User(models.Model):
    ip = models.CharField(max_length=25, default="RADOM")
    def __str__(self):
        return self.ip

class Answer(models.Model):
    Text_of_Answer = models.CharField(max_length=255)
    Answer_To_Question = models.ForeignKey(Name_of_Question, on_delete=models.CASCADE, default=None)
    Number_Of_Answer = models.IntegerField(default=0)
    def __str__(self):
        return self.Text_of_Answer

class Who_Answer(models.Model):
    Who_Answer = models.ManyToManyField(User, default="None")
    Where_Answer = models.ManyToManyField(Name_of_Question,related_name=None, default=None)
    Who_Answer = models.ForeignKey(User, on_delete=models.CASCADE)
    How_Many = models.IntegerField(default=0)

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
{% load static %}
<h1>  {{question.Text_of_Question}} </h1>
<h1> MAMAO</h1>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
{% if latest_question_list %}
    <ul>
    {% for Name_of_quiz in latest_question_list %}
    <li><a href="{% url 'polls:detail' Name_of_Question.id %}">{{ Name_of_Question.Text_of_Question }}</a> ----> {{Name_of_quiz.Grand}}</li>


        </li>

    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1> {{pytanie.question_1}}</h1>

<ul>
{% for choice in pytanie.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' pytanie.id %}">Vote again?</a>